const SUPABASE_URL='https://qjcizyvqragfunckbgjz.supabase.co';
const SUPABASE_KEY='sb_publishable_Swd1Yy8mb63vrK6vIildvg_orjmBY0l';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const cfg=window.SITE_CONFIG;
let posts=[];
const $=s=>document.querySelector(s);
function clientToken(){let t=localStorage.getItem('community_client_token');if(!t){t=crypto.randomUUID();localStorage.setItem('community_client_token',t)}return t}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(d){return new Date(d).toLocaleDateString('ja-JP',{year:'numeric',month:'short',day:'numeric'})}
function renderMeta(m={}){return Object.entries(m).filter(([,v])=>v!==''&&v!=null).slice(0,4).map(([k,v])=>`<span class="pill">${esc(cfg.metaLabels?.[k]||k)}: ${esc(v)}</span>`).join('')}
function filtered(){const q=$('#search').value.trim().toLowerCase();const cat=$('#categoryFilter').value;return posts.filter(p=>(!cat||p.category===cat)&&(!q||`${p.title} ${p.body} ${p.location||''} ${p.category}`.toLowerCase().includes(q)))}
function render(){const list=filtered();$('#count').textContent=posts.length;$('#list').innerHTML=list.length?list.map(p=>`<article class="card"><div class="meta"><span class="pill">${esc(p.category)}</span>${p.location?`<span>📍 ${esc(p.location)}</span>`:''}<span>${fmt(p.created_at)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p><div class="meta">${renderMeta(p.metadata)}</div><div class="actions"><button onclick="helpful('${p.id}',this)">👍 役に立った ${p.helpful_count}</button><button onclick="reportPost('${p.id}')">⚑ 通報</button></div></article>`).join(''):'<div class="empty">まだ投稿がありません。最初の体験を共有してみてください。</div>'}
async function load(){const {data,error}=await db.from('community_posts').select('*').eq('site',cfg.site).order('created_at',{ascending:false}).limit(200);if(error){$('#list').innerHTML='<div class="error">読み込みに失敗しました。</div>';return}posts=data||[];render()}
async function helpful(id,btn){btn.disabled=true;const {data}=await db.rpc('community_helpful',{post_id:id,client_token:clientToken()});const p=posts.find(x=>x.id===id);if(p&&typeof data==='number'){p.helpful_count=data;render()}}
async function reportPost(id){if(!confirm('この投稿を不適切な内容として通報しますか？'))return;await db.rpc('community_report',{post_id:id,client_token:clientToken()});alert('通報を受け付けました。');await load()}
function buildForm(){const meta=(cfg.fields||[]).map(f=>`<div><label>${esc(f.label)}</label><input name="meta_${esc(f.key)}" placeholder="${esc(f.placeholder||'')}" ${f.required?'required':''}></div>`).join('');$('#submitForm').innerHTML=`<h2>体験を投稿する</h2><div class="form-grid"><div><label>タイトル</label><input name="title" maxlength="160" required placeholder="${esc(cfg.titlePlaceholder)}"></div><div><label>カテゴリ</label><select name="category">${cfg.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><label>${esc(cfg.locationLabel||'地域・場所')}</label><input name="location" placeholder="${esc(cfg.locationPlaceholder||'任意')}"></div>${meta}</div><label>詳しい体験・役立ったこと</label><textarea name="body" maxlength="5000" required placeholder="${esc(cfg.bodyPlaceholder)}"></textarea><p class="notice">個人情報、住所、電話番号、氏名などは書かないでください。事実ベースの体験を共有してください。</p><button class="button" type="submit">投稿する</button><div id="msg"></div>`}
async function submit(e){e.preventDefault();const fd=new FormData(e.target);const metadata={};for(const f of cfg.fields||[])metadata[f.key]=fd.get('meta_'+f.key)||'';const payload={site:cfg.site,title:fd.get('title'),body:fd.get('body'),category:fd.get('category'),location:fd.get('location')||null,metadata};$('#msg').innerHTML='';const {error}=await db.from('community_posts').insert(payload);if(error){$('#msg').innerHTML='<div class="error">投稿できませんでした。内容を確認してください。</div>';return}e.target.reset();$('#msg').innerHTML='<div class="success">投稿しました。あなたの体験が次の人の助けになります。</div>';await load()}
document.addEventListener('DOMContentLoaded',()=>{$('#siteTitle').textContent=cfg.title;$('#siteLead').textContent=cfg.lead;$('#siteBadge').textContent=cfg.badge;$('#categoryFilter').innerHTML='<option value="">すべてのカテゴリ</option>'+cfg.categories.map(c=>`<option>${esc(c)}</option>`).join('');buildForm();$('#submitForm').addEventListener('submit',submit);$('#search').addEventListener('input',render);$('#categoryFilter').addEventListener('change',render);load()});
window.helpful=helpful;window.reportPost=reportPost;