"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Post={id:number;category:string;body:string;empathy:number;same:number;createdAt:string};
const categories=["すべて","学校","仕事","家族","人間関係","社会","日常","その他"];
const prompts=["最近『それ、必要？』と思ったルールは？","言えなかったけれど、本当は伝えたかったことは？","今日いちばん小さくイラッとしたことは？","もっとこうだったら楽なのに、と思うことは？"];
const samples:Post[]=[{id:-1,category:"学校",body:"『みんな同じペースでできるはず』という空気、ちょっと苦しい。得意なことも時間のかかることも、人それぞれなのに。",empathy:128,same:46,createdAt:"少し前"},{id:-2,category:"仕事",body:"会議のための会議が多すぎる。30分で決められることを、資料づくりに3日かけている気がする。",empathy:94,same:31,createdAt:"今日"},{id:-3,category:"日常",body:"駅のエスカレーター、急ぐ人と立つ人がぶつからずに済む仕組みがもっと広まってほしい。",empathy:67,same:20,createdAt:"昨日"}];
export default function Home(){
 const[posts,setPosts]=useState<Post[]>(samples),[category,setCategory]=useState("すべて"),[sort,setSort]=useState<"new"|"popular"|"saved">("new"),[query,setQuery]=useState(""),[body,setBody]=useState(""),[postCategory,setPostCategory]=useState("日常"),[open,setOpen]=useState(false),[afterPost,setAfterPost]=useState(false),[notice,setNotice]=useState(""),[saved,setSaved]=useState<number[]>([]),[reacted,setReacted]=useState<string[]>([]),[promptIndex,setPromptIndex]=useState(0);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setSaved(JSON.parse(localStorage.getItem("moyabara-saved")||"[]"));setReacted(JSON.parse(localStorage.getItem("moyabara-reacted")||"[]"))}catch{}fetch("/api/posts").then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(d.posts?.length)setPosts(d.posts)}).catch(()=>{})},0);return()=>window.clearTimeout(timer)},[]);
 const shown=useMemo(()=>posts.filter(p=>category==="すべて"||p.category===category).filter(p=>p.body.toLowerCase().includes(query.toLowerCase())).filter(p=>sort!=="saved"||saved.includes(p.id)).sort((a,b)=>sort==="popular"?(b.empathy+b.same)-(a.empathy+a.same):b.id-a.id),[posts,category,query,sort,saved]);
 const trends=useMemo(()=>categories.slice(1).map(name=>({name,count:posts.filter(p=>p.category===name).length})).sort((a,b)=>b.count-a.count).slice(0,4),[posts]),maxTrend=Math.max(...trends.map(t=>t.count),1);
 function toast(m:string){setNotice(m);window.setTimeout(()=>setNotice(""),3200)}
 function startWithPrompt(){setBody(prompts[promptIndex]+"\n");setOpen(true)}
 async function submit(e:FormEvent){e.preventDefault();const clean=body.trim();if(clean.length<10)return toast("もう少しだけ詳しく書いてみてください（10文字以上）。");const r=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:clean,category:postCategory})}),d=await r.json();if(!r.ok)return toast(d.error||"投稿できませんでした。少し時間をおいて試してください。");setPosts(p=>[d.post,...p.filter(x=>x.id>0)]);setBody("");setOpen(false);setAfterPost(true)}
 async function react(id:number,kind:"empathy"|"same"){const key=`${id}-${kind}`;if(reacted.includes(key))return toast("その気持ちは、もう届けています。");const next=[...reacted,key];setReacted(next);localStorage.setItem("moyabara-reacted",JSON.stringify(next));setPosts(ps=>ps.map(p=>p.id===id?{...p,[kind]:p[kind]+1}:p));if(id>0)await fetch(`/api/posts/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:kind})})}
 function save(id:number){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem("moyabara-saved",JSON.stringify(next));toast(saved.includes(id)?"保存から外しました。":"あとで見返せるよう保存しました。")}
 async function report(id:number){if(id>0)await fetch(`/api/posts/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"report"})});toast("通報を受け付けました。内容を確認します。")}
 return <main><header className="topbar"><a className="brand" href="#top"><span>もや</span>ばら</a><nav><a href="#feed">みんなの声</a><a href="#trends">今日の傾向</a><a href="#about">約束</a></nav><button className="primary small" onClick={()=>setOpen(true)}>＋ もやもやを書く</button></header>
 <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">言えなかったことを、ここに置いていく。</p><h1>その「なんか嫌だ」、<br/><em>あなただけじゃない。</em></h1><p className="lead">学校、仕事、人間関係、社会のこと。匿名で吐き出して、誰かの「わかる」と出会える場所です。</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}>もやもやを手放す　→</button><a href="#feed">みんなの声を見る</a></div><p className="safe-note">名前もアカウントも不要。個人が特定できる内容は書かないでください。</p></div><div className="cloud-art" aria-hidden="true"><span className="cloud c1">もや</span><span className="cloud c2">うーん…</span><span className="cloud c3">なんで？</span><div className="sun">ふぅ。</div></div></section>
 <section className="prompt-band"><div><span>今日の書き出し</span><p>{prompts[promptIndex]}</p></div><div><button className="shuffle" onClick={()=>setPromptIndex(i=>(i+1)%prompts.length)}>↻ 別のお題</button><button className="outline" onClick={startWithPrompt}>このお題で書く →</button></div></section>
 <section className="feed" id="feed"><div className="section-head"><div><p className="eyebrow">VOICES</p><h2>いま、届いている声</h2></div><div className="stats"><b>{posts.length+1247}</b><span>件のもやもや</span></div></div><div className="toolbar"><div className="chips">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="tools"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="声を検索"/></label><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="new">新着順</option><option value="popular">共感順</option><option value="saved">保存した声</option></select></div></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="cards">{shown.map(post=><article className="card" key={post.id}><div className="card-meta"><span className={`tag tag-${post.category}`}>{post.category}</span><time>{post.createdAt}</time></div><p>{post.body}</p><div className="reactions"><button className={reacted.includes(`${post.id}-empathy`)?"done":""} onClick={()=>react(post.id,"empathy")}>☁ わかる <b>{post.empathy}</b></button><button className={reacted.includes(`${post.id}-same`)?"done":""} onClick={()=>react(post.id,"same")}>◌ 私も <b>{post.same}</b></button><button className={saved.includes(post.id)?"save done":"save"} onClick={()=>save(post.id)} aria-label="保存">{saved.includes(post.id)?"★":"☆"}</button><button className="report" onClick={()=>report(post.id)} aria-label="通報">…</button></div></article>)}{!shown.length&&<div className="empty"><b>ここには、まだ声がありません。</b><p>{sort==="saved"?"気になった声の☆を押すと、ここで見返せます。":"最初の声を置いてみませんか。"}</p></div>}</div></section>
 <section className="trend-section" id="trends"><div className="trend-copy"><p className="eyebrow">TODAY&apos;S MOYA</p><h2>今日、みんなが<br/>もやもやしていること。</h2><p>声を集計して、個人ではなく「社会の困りごと」として眺めます。声が増えるほど、見えなかった課題の輪郭が見えてきます。</p></div><div className="trend-panel">{trends.map((t,i)=><button key={t.name} onClick={()=>{setCategory(t.name);location.hash="feed"}}><span>{String(i+1).padStart(2,"0")}</span><b>{t.name}</b><i><u style={{width:`${Math.max(12,t.count/maxTrend*100)}%`}}/></i><small>{t.count}件</small></button>)}</div></section>
 <section className="about" id="about"><p className="eyebrow">OUR PROMISE</p><h2>誰かを傷つけるためではなく、<br/>気持ちを軽くするための場所。</h2><div className="promises"><div><b>01</b><h3>否定しない</h3><p>反論や採点はせず、「わかる」をそっと届けます。</p></div><div><b>02</b><h3>特定しない</h3><p>実名、連絡先、学校名など個人がわかる情報は投稿できません。</p></div><div><b>03</b><h3>攻撃しない</h3><p>差別や脅し、誰かを傷つける投稿は掲載しません。</p></div></div></section><footer><div className="brand"><span>もや</span>ばら</div><p>気持ちに、置き場所を。</p><p className="copyright">© 2026 Moyabara</p></footer>
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">LET IT OUT</p><h2>いま、何にもやもやしてる？</h2><p>うまくまとめなくて大丈夫。個人が特定できる名前や場所は書かないでください。</p><form onSubmit={submit}><label>カテゴリー<select value={postCategory} onChange={e=>setPostCategory(e.target.value)}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>あなたの声<textarea maxLength={300} value={body} onChange={e=>setBody(e.target.value)} placeholder="ここに、いま感じていることを…" autoFocus/></label><div className="counter"><span className={body.length>270?"warn":""}>{body.length} / 300</span></div><button className="primary" type="submit">匿名で投稿する →</button></form><p className="rules">投稿内容は安全のため自動確認されます。個人情報・攻撃的表現を含めないでください。</p></section></div>}
 {afterPost&&<div className="modal-backdrop"><section className="modal after"><div className="release-cloud">☁</div><p className="eyebrow">THANK YOU</p><h2>置いていって、だいじょうぶ。</h2><p>あなたの声は匿名で届きました。いまは少し画面から離れたり、ゆっくり息を吐いたりしても大丈夫です。</p><div className="after-actions"><button className="primary" onClick={()=>{setAfterPost(false);location.hash="feed"}}>届いた声を見る</button><button className="outline" onClick={()=>setAfterPost(false)}>このまま休む</button></div></section></div>}</main>}
